### ISSUE TITLE
serverside problems with multi-module projects

### ISSUE THREAD

**Issue by Laures** [versioneye/versioneye_maven_plugin#24]
for unknown reasons the server returns an invalid respons for a single module in multi module projects. once this has happend the first time the issue travels through the modules in their reactor ordering (the order in which maven builds the modules) with every build.

For example:

build X:

module1: success
module2: fail
module3: skipped

build X+1:

module1: success
module2: success
module3: fail

once the issue reached the last module it will vanish (so far it has not returned).
The behavior is persistent over machines (no surprise there).

mvn -e returns the following stacktrace:

```
[ERROR] Failed to execute goal com.versioneye:versioneye-maven-plugin:2.1.0-BATSU:update (default-cli) on project mvc: Oh no! Something went wrong. Get in touch with the VersionEye guys and give them
feedback.You find them on Twitter at https//twitter.com/VersionEye. Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
[ERROR] at [Source: java.io.InputStreamReader@76ce21e7; line: 1, column: 2]
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.versioneye:versioneye-maven-plugin:2.1.0-BATSU:update (default-cli) on project mvc: Oh no! Something went wrong. Get
in touch with the VersionEye guys and give them feedback.You find them on Twitter at https//twitter.com/VersionEye.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Oh no! Something went wrong. Get in touch with the VersionEye guys and give them feedback.You find them on Twitter at https//twitter.com/Vers
ionEye.
        at com.versioneye.UpdateMojo.execute(UpdateMojo.java:32)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
Caused by: org.codehaus.jackson.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.InputStreamReader@76ce21e7; line: 1, column: 2]
        at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1433)
        at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:521)
        at org.codehaus.jackson.impl.JsonParserMinimalBase._reportUnexpectedChar(JsonParserMinimalBase.java:442)
        at org.codehaus.jackson.impl.ReaderBasedParser._handleUnexpectedValue(ReaderBasedParser.java:1198)
        at org.codehaus.jackson.impl.ReaderBasedParser.nextToken(ReaderBasedParser.java:485)
        at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2770)
        at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2718)
        at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1886)
        at com.versioneye.UpdateMojo.uploadDependencies(UpdateMojo.java:45)
        at com.versioneye.UpdateMojo.execute(UpdateMojo.java:28)
        ... 21 more
```

NOTE: 2.1.0-BATSU is actually the current snapshot. i had to fix the version because our maven repository does not accept snapshots.

**Comment by reiz** [comment]
@Laures Can you please try again with the current version of the plugin, which is 3.7.0. Many Thanks!

**Comment by reiz** [comment]
I close this ticket because nobody else had this problems. I assume it's fixed in the current version.
